### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by mauro3** [pjabardo/CurveFit.jl#10]
Thanks!

**Comment by ufechner7** [comment]
Would be nice... Then a released version would work with Julia 1.0.

**Comment by pjabardo** [comment]
I honestly don't know how to do with version 1.0

    Em sexta-feira, 8 de março de 2019 09:51:36 BRT, Uwe Fechner <notifications@github.com> escreveu:  
 
 
Would be nice... Then a released version would work with Julia 1.0.

**Comment by mauro3** [comment]
Do you have attobot installed? https://github.com/attobot/attobot

**Comment by ufechner7** [comment]
But before tagging a new release check if the two open pull requests can be merged.

**Comment by pjabardo** [comment]
I will do that.

    Em terça-feira, 12 de março de 2019 08:13:46 BRT, Uwe Fechner <notifications@github.com> escreveu:  
 
 
But before tagging a new release check if the two open pull requests can be merged.

**Comment by pjabardo** [comment]
I have tagged a new version
