### ISSUE TITLE
Poly doesn't work with recent Polynomials.jl

### ISSUE THREAD

**Issue by uchkw** [pjabardo/CurveFit.jl#22]
From v0.8 of Polynomials.jl, the typename of Polynomial was changed to `Polynomial` from `Poly`.
Although the current CurveFit.jl recommends using v1.2 or v1.0 of Polynomials.jl, 
`curve_fit(Poly, x, y, n=1)` in the examples does not work.

If you change the typename like `curve_fit(Polynomial, x, y, n=1)`, it works.

**Comment by pjabardo** [comment]
You are correct. I need to improve the documentation in general and the README.md file in particular. I will change the file right now.

**Comment by pjabardo** [comment]
Just did it.
