### ISSUE TITLE
Could you provide an example of 3d curve fitting?

### ISSUE THREAD

**Issue by ruizhi92** [pjabardo/CurveFit.jl#28]
Although there are descriptions in the doc saying that "While usually x is a single variable, in general, if several independent variables are required, the same procedure can be used", I didn't get it to work.

I would like to fit two independent variables [x,y] with function value z by polynomials, i.e. 3d curve fitting or surface fitting in Matlab. Could you please provide an example? Thanks a lot.

**Comment by pjabardo** [comment]
So sorry it took this long to answer you! I didn't notice the issue!

There is the function CurveFit.fit_linear_model(Av,z). I forgot to export it.

Let me give you an example of its use:

```
using CurveFit

fun(x,y) = 1.0 + 0.5*x + 1.2*y - 0.7*x*y - 0.2*exp(x*y); # I want to find the coefficients 1, 0.5, 1.2, -0.7, -0.2
f1(x,y) = 1.0;  # each term for the linear fit
f2(x,y) = x;
f3(x,y) = y;
f4(x,y) = x*y;
f5(x,y) = exp(x*y);

# Generate random points
x = rand(100);
y = rand(100);
z = fun.(x, y);

A = hcat(f1.(x,y), f2.(x,y), f3.(x,y), f4.(x,y), f5.(x,y));

coefs = CurveFit.fit_linear_model(A, z);

coefs
5-element Vector{Float64}:
  1.0000000000000044
  0.4999999999999993
  1.1999999999999984
 -0.6999999999999931
 -0.20000000000000379

```


I hope this helps

**Comment by ruizhi92** [comment]
Thank you for giving the example! I believe other users would find it helpful if you put it in docs.

**Comment by pjabardo** [comment]
I need to take better care of the package. Better docs and some improvements. Once I have some free time I will do this.
