### ISSUE TITLE
Example not working 

### ISSUE THREAD

**Issue by steffenkaminski** [pjabardo/CurveFit.jl#29]
Example mentioned on the readme currently not executable

```
using PyPlot
using CurveFit

x = 0.0:0.02:2.0
y0 = @. 1 + x + x*x + randn()/10
fit = curve_fit(Polynomial, x, y0, 2)
y0b = fit.(x) 
plot(x, y0, "o", x, y0b, "r-", linewidth=3)

```
Polynomial doesnt seem to be exported by the module.

`    fit = curve_fit(CurveFit.Polynomial,  x, y0, 2)`

works.

**Comment by pjabardo** [comment]
You are correct. I will reexport Polynomial and tag a new version.

Thanks
Paulo
