### ISSUE TITLE
Example of non-linear code

### ISSUE THREAD

**Issue by jmarcellopereira** [pjabardo/CurveFit.jl#4]
I wish someone would publish a non-linear fitting code

**Comment by pjabardo** [comment]
The package has non-linear fitting code, implemented in function

 nonlinear_fit(x, fun, a0, eps=1e-8, maxiter=200)

An example can be seen in file https://github.com/pjabardo/CurveFit.jl/blob/master/src/king.jl

in function king_fit

**Comment by jmarcellopereira** [comment]
Too complicated....
using this data, how we can use CurveFit?

x = [0.0 0.2 0.4 1.0 1.6 1.8 2.0 2.6 2.8 3.0 3.8 4.8 5.0 5.2 6.0 6.2 7.4 7.6 7.8 8.6 8.8 9.0 9.2 9.4 10.0 10.6 10.8 11.2 11.6 11.8 12.2 12.4];

y = [-0.183 -0.131 0.027 0.3 0.579 0.853 0.935 1.133 1.269 1.102 1.092 1.143 0.811 0.91 0.417 0.46 -0.516 -0.334 -0.504 -0.946 -0.916 -0.975 -1.099 -1.113 -1.297 -1.234 -0.954 -1.122 -0.609 -0.593 -0.403 -0.51];

**Comment by jmarcellopereira** [comment]
x = [0  0.200  0.400  1.000  1.6000  1.800  2.000  2.600  2.800  3.00000000000000  3.80000000000000  4.80000000000000  5.00000000000000  5.20000000000000  6.00000000000000  6.20000000000000  7.40000000000000  7.60000000000000  7.80000000000000  8.60000000000000  8.80000000000000  9.00000000000000  9.20000000000000  9.40000000000000  10.0000000000000  10.6000000000000  10.8000000000000  11.2000000000000  11.6000000000000  11.8000000000000  12.2000000000000  12.4000000000000];
y = [-0.183440428023042  -0.131101157495126  0.0268875670852843  0.300000000120000  0.579048247883555  0.852605831272159  0.935180993484717  1.13328608090532  1.26893326843583  1.10202945535186  1.09201137189664  1.14279083803453  0.811302535321072  0.909735376251797  0.417067545528244  0.460107770989798  -0.516307074859654  -0.333994077331822  -0.504124744955962  -0.945794320817293  -0.915934553082780  -0.975458595671737  -1.09943707404275  -1.11254211607374  -1.29739980589100  -1.23440439602665  -0.953807504156356  -1.12240274852172  -0.609284630192522  -0.592560286759450  -0.402521296049042  -0.510090363150962];
